# Generated by Django 5.0.3 on 2024-03-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('event', 'participant')},
        ),
    ]
