# Generated by Django 5.0.3 on 2024-03-23 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_register', '0003_alter_participant_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['timestamp']},
        ),
    ]
